name: CI + Deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - run: pip install -r requirements.txt
      - run: pytest -q
      - run: python train.py
      - uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: artifacts/

  deploy-pages:
    needs: test-and-train
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: model-and-metrics
          path: artifacts
      - name: Generate HTML report
        run: |
          python - <<'PY'
          import json, pathlib
          m = json.load(open('artifacts/metrics.json'))
          pathlib.Path('public').mkdir(exist_ok=True)
          open('public/index.html','w').write(f"<h1>Accuracy: {m['accuracy']:.3f}</h1>")
          PY
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4